# Builds app
#
# Triggered manually 
#

name: build app

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: create venv
        run: python3 -m venv venv && source venv/bin/activate
      
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: build
        run: pyinstaller --noconfirm --onefile --windowed --add-data "rsc:rsc/"  "App.py" --name "SweatboxScenarioGenerator"
        
      - name: Upload build as Artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: Sweatbox-Scenario-Generator
          path: dist
      

    